### ISSUE TITLE
Modules over 2GB cannot be uploaded to ShotGrid

### ISSUE THREAD

**Issue by fabiangeisler** [cpenv/cpenv#68]
If you try to upload a module which is bigger than 256 MB cpenv will crash with this error:
```
Traceback (most recent call last):
  File "/home/fabian.geisler/.local/bin/cpenv", line 8, in <module>
    sys.exit(main())
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/__main__.py", line 19, in main
    core.run(cli.CpenvCLI, sys.argv[1:])
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/cli/core.py", line 336, in run
    return run(cli_command, args)
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/cli/core.py", line 350, in run
    return cli.run(args)
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/cli/publish.py", line 55, in run
    published = to_repo.upload(module, args.overwrite)
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/repos/shotgun.py", line 233, in upload
    entity = self.shotgun.create(self.module_entity, data)
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/vendor/shotgun_api3/shotgun.py", line 1329, in create
    record = self._call_rpc("create", params, first=True)
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/vendor/shotgun_api3/shotgun.py", line 3360, in _call_rpc
    self._response_errors(response)
  File "/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/vendor/shotgun_api3/shotgun.py", line 3665, in _response_errors
    raise Fault(sg_response.get("message", "Unknown Error"))
cpenv.vendor.shotgun_api3.shotgun.Fault: API create() CRUD ERROR #6: Create failed for [CustomNonProjectEntity03]: PG::NumericValueOutOfRange: ERROR:  value "2367519769" is out of range for type integer
```

## Issue cause
The `sg_archive_size` field on the Module entity is of type "number" which does not accept integers bigger than 2.147.483.647. Since `cpenv` tracks the size of the uploaded package in bits, we reach this limit at 256MB. 

## Closing thoughts
The area of AI has one unfortunate downside which is big file sizes for their trained models. So it is reasonable to assume that some plugins/modules will be bigger than 256 MB. Current examples: [NNFlowVector](https://www.pixelmania.se/products/nnflowvector/) with 4.1GB per Nuke version and [NNSuperResolution](https://www.pixelmania.se/products/nnsuperresolution/) with 6.1GB per Nuke version.

**Comment by danbradham** [comment]
Hmmm, we have many modules larger than 256mb in our SG site. Let me check our sg_archive_size field.

**Comment by danbradham** [comment]
Our largest module is 1.5gb or 1,500,000,000 bytes. It seems the limit of the Number field is closer to 2,000,000,000, so, we just got lucky.

The simplest solution would probably be to switch the sg_archive_size field to text. I'll investigate this weekend.

**Comment by fabiangeisler** [comment]
Ah I miscalculated there. I thought you tracked bits not bytes. So the limit is actually 2 GB at the moment. I'll adjust the headline.
