### ISSUE TITLE
Windows:  remove module errors

### ISSUE THREAD

**Issue by mgcollie** [cpenv/cpenv#7]
C:\Windows\system32>cpenv create test
Creating new environment test

Upgrading cpenv
Collecting cpenv
  Using cached cpenv-0.3.2-py2.py3-none-any.whl
Installing collected packages: cpenv
Successfully installed cpenv-0.3.2
Requirement already satisfied: cpenv in c:\users\mcollie\.cpenv\test\lib\site-packages
Collecting virtualenv (from cpenv)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-15.1.0
Activating test
[test] C:\Windows\system32>cpenv create --module maya2016 https://github.com/cpenv/maya_module.git

Installing https://github.com/cpenv/maya_module.git
Cloning into 'C:\Users\mcollie\.cpenv\test\modules\maya2016'...
remote: Counting objects: 35, done.
remote: Total 35 (delta 0), reused 0 (delta 0), pack-reused 35
Unpacking objects: 100% (35/35), done.

[test] C:\Windows\system32>cpenv remove --module maya2016
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\mcollie\.cpenv\test\Scripts\cpenv.exe\__main__.py", line 9, in <module>
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\packages\click\core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\packages\click\core.py", line 590, in main
    rv = self.invoke(ctx)
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\packages\click\core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\packages\click\core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\packages\click\core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\__main__.py", line 119, in remove
    active_env.rem_module(name_or_path)
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\models.py", line 300, in rem_module
    module.remove()
  File "C:\Users\mcollie\.cpenv\test\Lib\site-packages\cpenv\models.py", line 375, in remove
    shutil.rmtree(self.path)
  File "c:\python27\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\python27\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\python27\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\python27\Lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\Lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: 'C:\\Users\\mcollie\\.cpenv\\test\\modules\\maya2016\\.git\\objects\\0d\\c07d1c0843a60012d585616e9f99cb633c57cc'

[test] C:\Windows\system32>

**Comment by danbradham** [comment]
Implemented a fix based on this dicussion: https://bugs.python.org/issue19643
Included in 0.3.3 now available on pypi

**Comment by mgcollie** [comment]
Very quick fix Dan.  Much appreciated
